version: '3'
services:
  elastic-search:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

networks:
  elastic:
  rabbitmq_go_net:
    driver: bridge